name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Setup requirements
        run: make pip
      - name: Codestyle
        run: python -m black -v --check .
      - name: Lint
        run: make lint
      - name: Running tests
        run: make test

